language: node_js
node_js:
  - '8'

cache:
  directories:
    - "node_modules"

before_install: npm install -g grunt-cli codeclimate-test-reporter

sudo: false

#after_script:
#  - codeclimate < build/lcov.info
