name: Node.js CI

on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Grunt cli
      run: npm install -g grunt-cli
      
    - name: Install other dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
      env:
        CI: true

    - run: npm run build --if-present

